columnSuffix: wlsfkuxa
contentColumnType: string(255)
fieldGroup: 2b7e21f1-7e16-43d4-8403-4bf42f4d4b25 # Common
handle: signIn
instructions: ''
name: 'Sign In'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: site
type: craft\fields\Url
