defaultPlacement: end
enableVersioning: true
handle: location
name: Location
propagationMethod: all
siteSettings:
  249fcb65-9cc4-43c6-855a-adb81fba7d17: # Craft
    enabledByDefault: true
    hasUrls: true
    template: location/_entry
    uriFormat: '{slug}'
type: channel
